# Generated by Django 6.0.3 on 2026-04-11 05:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_user_gst_number_alter_user_ifsc_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sample_media',
            field=models.FileField(blank=True, help_text='Upload sample images, floorplans, or references', null=True, upload_to='project_samples/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Stored as: +919876543210', max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\+?[1-9]\\d{6,14}$', 'Enter a valid phone number with country code.')]),
        ),
    ]
