# Generated by Django 6.0.3 on 2026-04-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_projectmedia_proposalmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='revision_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
