# Generated by Django 6.0.3 on 2026-04-12 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_messagereadstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
        migrations.AddField(
            model_name='project',
            name='location_custom',
            field=models.CharField(blank=True, help_text="Used if 'Other' is selected", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ban_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='violation_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.venue'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_inspectors', to='core.venue'),
        ),
    ]
