# Generated by Django 6.0.3 on 2026-05-03 17:57

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_venue_remove_project_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Publicly visible bio. No contact details allowed.', null=True, validators=[core.models.validate_no_contact_info]),
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[core.models.validate_no_contact_info])),
                ('description', models.TextField(blank=True, null=True, validators=[core.models.validate_no_contact_info])),
                ('image', models.ImageField(upload_to='portfolio_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
