# Generated by Django 6.0.3 on 2026-05-03 18:03

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_user_bio_portfolioitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True, validators=[core.models.validate_no_contact_info]),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/', validators=[core.models.validate_image_no_contact_info]),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/', validators=[core.models.validate_image_no_contact_info]),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(upload_to='portfolio_images/', validators=[core.models.validate_image_no_contact_info]),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(validators=[core.models.validate_no_contact_info]),
        ),
        migrations.AlterField(
            model_name='project',
            name='preferred_materials',
            field=models.TextField(blank=True, null=True, validators=[core.models.validate_no_contact_info]),
        ),
        migrations.AlterField(
            model_name='project',
            name='sample_media',
            field=models.FileField(blank=True, help_text='Upload sample images, floorplans, or references', null=True, upload_to='project_samples/', validators=[core.models.validate_image_no_contact_info]),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255, validators=[core.models.validate_no_contact_info]),
        ),
        migrations.AlterField(
            model_name='project',
            name='venue_details',
            field=models.TextField(blank=True, null=True, validators=[core.models.validate_no_contact_info]),
        ),
        migrations.AlterField(
            model_name='projectmedia',
            name='file',
            field=models.FileField(upload_to='project_media/', validators=[core.models.validate_image_no_contact_info]),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='description',
            field=models.TextField(validators=[core.models.validate_no_contact_info]),
        ),
        migrations.AlterField(
            model_name='proposalmedia',
            name='file',
            field=models.FileField(upload_to='proposal_media/', validators=[core.models.validate_image_no_contact_info]),
        ),
    ]
