# Generated by Django 6.0.3 on 2026-05-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_project_payment_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='agree_to_release_payment',
            field=models.BooleanField(default=False),
        ),
    ]
